name: Create paper website on gh-pages branch

on:
  push:
    branches:
    - paper
    paths:
    - 'paper/*'
    - '.github/workflows/build-website.yml'
    - '.github/utils/papersetup.sh'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 1
    - uses: jayanthkoushik/build-webpage@master
      with:
        setupscript: sh .github/utils/papersetup.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
