name: Create paper website on gh-pages branch

on:
  push:
    branches:
    - master
    paths:
    - 'paper/*'
    - '!paper/main.pdf'
    - '.github/workflows/build-website.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: jayanthkoushik/paje@v6.2.1
      with:
        setupscript: |
          cp paper/main.md /www/index.md
          cp paper/references.bib /www/_includes/
          cp paper/commands.md /www/_includes/
          mkdir -p /www/fig
          cp paper/fig/alg.svg /www/fig/
          cp paper/fig/mnist.svg /www/fig/
          cp paper/fig/synth.svg /www/fig/
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
