name: Create paper website on gh-pages branch

on:
  push:
    branches:
    - master
    paths:
    - 'paper/*'
    - '!paper/main.pdf'
    - '.github/workflows/build-website.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: jayanthkoushik/paje@v1
      with:
        setupscript: |
          cp paper/main.md /www/index.md
          cp paper/references.bib /www/_includes/
          cp paper/commands.md /www/_includes/
          mkdir -p /www/fig
          convert -antialias -density 300 -quality 100 paper/fig/alg.pdf /www/fig/alg.png
          convert -antialias -density 300 -quality 100 paper/fig/synth.pdf /www/fig/synth.png
          convert -antialias -density 300 -quality 100 paper/fig/mnist.pdf /www/fig/mnist.png
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
